"""Initial migration: Blogger and Project models

Revision ID: 405eadad6686
Revises: 
Create Date: 2025-11-01 09:20:57.079126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '405eadad6686'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('frontal_image_url', sa.String(length=512), nullable=True),
    sa.Column('location_image_url', sa.String(length=512), nullable=True),
    sa.Column('tone_of_voice', sa.Text(), nullable=True),
    sa.Column('elevenlabs_voice_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blogger_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('scenario_text', sa.Text(), nullable=True),
    sa.Column('voiceover_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('audio_alignment', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('materials', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('timeline', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('avatar_video_url', sa.String(length=512), nullable=True),
    sa.Column('avatar_generation_params', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('final_video_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blogger_id'], ['bloggers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('bloggers')
    # ### end Alembic commands ###
